# Generated by Django 3.0.2 on 2020-06-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('temp_in', models.FloatField()),
                ('temp_out', models.FloatField()),
                ('humidity_in', models.FloatField()),
                ('humidity_out', models.FloatField()),
                ('pressure_abs', models.FloatField()),
                ('pressure_rel', models.FloatField()),
                ('wind_dir', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('wind_gust', models.FloatField()),
                ('wind_max_daily_gust', models.FloatField()),
                ('rain_rate', models.FloatField()),
                ('rain_event', models.FloatField()),
                ('rain_hourly', models.FloatField()),
                ('rain_daily', models.FloatField()),
                ('rain_weekly', models.FloatField()),
                ('rain_monthly', models.FloatField()),
                ('rain_total', models.FloatField()),
                ('solar_radiation', models.FloatField()),
                ('uv_index', models.FloatField()),
                ('station_type', models.CharField(max_length=50)),
            ],
        ),
    ]
